#!/usr/bin/env python3
"""Generate the Open Cross scenario configs (K-ARC arXiv:2501.01559 §V-B-1).

    python scripts/gen_open_cross.py             # all of N = 2, 4, 8, 16, 32
    python scripts/gen_open_cross.py --n 8       # just one

Writes conf/env/open_cross_{N}_unicycle2.yaml. N=2 is regenerated as a self-check only
(it must come out equal to the hand-written swap2_unicycle2.yaml) and is not written
unless asked for explicitly.
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.obs.full_state import FullStateObsBuilder  # noqa: E402

SIZES = (2, 4, 8, 16, 32)
S_Y = 1.0        # row spacing = unicycle_db turning radius v_max/omega_max = 0.5/0.5
MARGIN = 1.0     # clear space between the outermost row and the wall
TRAVERSE = 3.0   # start-to-goal distance, held constant across N (see header below)
# Uniform across N, and forced rather than chosen: N=32 needs 15*S_Y + 2*MARGIN. Sizing
# each N to its own row block instead would make free area per robot NON-MONOTONIC
# (6.25, 3.13, 5.06, 9.03 m^2 at N = 4, 8, 16, 32 -- the largest instance the roomiest),
# so a curve against N would not be measuring congestion. One world gives 289/N exactly.
WORLD = 17.0
PI = 3.14159

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "conf" / "env" / "swap2_unicycle2.yaml"
ROBOT = ROOT / "conf" / "robot" / "unicycle_db.yaml"


def num(v: float) -> str:
    """Format a float so it still reads as a float: 1 -> '1.0', 2.5 -> '2.5'."""
    s = f"{v:.6g}"
    return s if ("." in s or "e" in s) else s + ".0"


def geometry(n: int):
    """(world_size, x_left, x_right, [y per row]) for N robots in N/2 head-on rows."""
    if n < 2 or n % 2:
        raise ValueError(f"N must be even and >= 2, got {n}")
    rows = n // 2
    needed = (rows - 1) * S_Y + 2 * MARGIN
    if needed > WORLD:
        raise ValueError(
            f"N={n} needs {num(needed)} m of world at row spacing {num(S_Y)}, WORLD is "
            f"{num(WORLD)}. Raise WORLD -- do NOT shrink S_Y, it is already close to the "
            f"unicycle_db body diagonal."
        )
    cx = WORLD / 2
    ys = [cx + (k - (rows - 1) / 2) * S_Y for k in range(rows)]
    return WORLD, cx - TRAVERSE / 2, cx + TRAVERSE / 2, ys


def render(n: int) -> str:
    world, x_left, x_right, ys = geometry(n)
    rows = len(ys)
    obs_dim = FullStateObsBuilder(n, 0, world, n_dyn=2).obs_dim()
    max_steps = 300 if n <= 8 else 600
    area = world ** 2 / n

    agents = []
    for k, y in enumerate(ys):
        # Left robot drives +x at theta=0; right robot drives -x at theta=pi. Heading is
        # held at start AND goal, so neither robot has to turn around — same convention as
        # swap2_unicycle2.yaml, and the reason this is a pure translation conflict.
        agents.append((2 * k, x_left, y, 0.0, x_right))
        agents.append((2 * k + 1, x_right, y, PI, x_left))
    agent_block = "\n".join(
        f"  - id: agent_{i}\n"
        f"    start: [{num(xs)}, {num(y)}, {num(th)}, 0.0, 0.0]\n"
        f"    goal:  [{num(xg)}, {num(y)}, {num(th)}, 0.0, 0.0]\n"
        f"    robot: unicycle_db"
        for i, xs, y, th, xg in agents
    )

    return f"""\
# @package env
# K-ARC "Open Cross" (arXiv:2501.01559 §V-B-1) ported as a scenario at N={n}.
# GENERATED by scripts/gen_open_cross.py — edit the script, not this file.
#
# Their description of the benchmark, in full: "robots on the same row need to swap
# positions in an empty environment". So {rows} row{'' if rows == 1 else 's'}, each holding one head-on pair that
# swaps across the workspace, mirrored about the vertical centreline x={num(world / 2)}.
# Row spacing {num(S_Y)} m = the unicycle_db turning radius v_max/omega_max = 0.5/0.5.
#
# KNOWN DEVIATIONS. This is a SCENARIO PORT, not a benchmark reproduction. K-ARC
# publishes no workspace dimensions, no d_min, no segment count, no timestep and no
# velocity limits, and runs C++ on a 32-core i9-14900K. Our runtimes are NOT comparable
# to their published ones and must not be reported as if they were.
#   world      - square, {num(world)} x {num(world)}. `world_size` is a single scalar and
#                src/obs/full_state.py:96-99 uses it for both axes, so the wide short box
#                of their Fig. 2(a) is not expressible here.
#   traverse   - held at {num(TRAVERSE)} m for every N on purpose, so runtime against N
#                measures congestion, not distance.
#   robot      - conf/robot/unicycle_db.yaml (dynobench unicycle2_v0); its own deviations
#                from db-CBS are listed in that file.
#   reward     - ours. K-ARC is a planner and carries no reward.
#   max_steps  - ours. The benchmark has no horizon.
#   goal test  - position radius + speed gate, inherited from swap2_unicycle2.yaml.
#
# NOTE: every row is a SYMMETRIC head-on pair — the conflict swap2_unicycle2.yaml:15-17
# records as unsolved. A shared-weights policy sees mirrored observations and produces
# mirrored actions, so expect pairs to drive into each other. That is a result to log
# (per-row collision rate), not a bug to fix by offsetting the lanes.
#
# The world is the SAME {num(world)} x {num(world)} at every N and only the robot count changes,
# so free area per robot is {num(WORLD ** 2)}/N = {area:.2f} m^2 here, and falls monotonically
# across the sweep. Sizing each N to its own row block instead would make it
# NON-monotonic — 6.25, 3.13, 5.06, 9.03 m^2 at N = 4, 8, 16, 32, the largest instance the
# roomiest — and would also rescale the wall-distance observations, which full_state.py
# divides by world_size. Either one confounds a curve plotted against N.
#
# Observation is 11 + 2*(N-1) = {obs_dim} wide, so a policy trained here will not load at a
# different N. Every N is its own run.
# Prefer shaping=braking or shaping=euclidean, not dijkstra: the world is empty, so the
# grid buys nothing and costs one solve per agent per env.
# Collision checking is O(N^2) — time one episode before queueing a long run at N=32.
world_size: {num(world)}
dt: 0.1              # dynobench unicycle2_v0 dt
max_steps: {max_steps}       # {num(max_steps * 0.1)} s; the {num(TRAVERSE)} m traverse at v_max=0.5 needs >= 6 s plus braking
goal_radius: 0.2

reward:
  reach: 50.0
  collision: -2.0
  step_penalty: -0.01
  shaping_scale: 4.0
  effort_penalty: -0.002
  # coef*ω² per step, coef <= 0. effort_penalty charges angular ACCEL, so a constant-rate spin
  # (α=0) is free without this. 0.04*omega_max² = 0.04*0.5² = 0.01 = |step_penalty|,
  # i.e. a sustained full-rate spin costs about one extra step.
  omega_penalty: -0.04

omega_max_override: null
terminate_on_collision: false
require_stop_at_goal: true
# Inherited from swap2_unicycle2.yaml — see the DEVIATION note there on why the speed gate
# is this loose (the benchmark's weighted state-space distance permits |dv| <~ 0.4).
stop_speed: 0.4

obstacles: []

agents:
{agent_block}
"""


def check() -> None:
    """N=2 must be swap2_unicycle2.yaml, re-centred in the uniform world.

    swap2 was ported by hand from db-CBS into its own 5.0 m world; ours is WORLD for every
    N, so the one licensed difference is a rigid translation of (WORLD - 5.0)/2 on both
    axes. Everything else — every reward field, every flag, both headings, the 3.0 m
    traverse — has to match the real file, so the two cannot drift apart.
    """
    ref = yaml.safe_load(REFERENCE.read_text())
    got = yaml.safe_load(render(2))
    shift = (WORLD - ref["world_size"]) / 2

    assert got["world_size"] == WORLD, got["world_size"]
    for key in ("dt", "max_steps", "goal_radius", "stop_speed", "omega_max_override",
                "terminate_on_collision", "require_stop_at_goal", "obstacles", "reward"):
        assert got[key] == ref[key], f"N=2 {key}: {got[key]!r} != swap2's {ref[key]!r}"

    assert len(got["agents"]) == 2, got["agents"]
    for g, r in zip(got["agents"], ref["agents"]):
        assert g["id"] == r["id"] and g["robot"] == r["robot"], (g, r)
        for field in ("start", "goal"):
            # Translate x and y, leave theta and the two zero velocities alone. theta only
            # to 2dp: swap2 writes db-CBS's literal 3.14, we write 3.14159.
            want = [r[field][0] + shift, r[field][1] + shift, *r[field][2:]]
            assert all(abs(a - b) < 2e-3 for a, b in zip(g[field], want)), \
                f"N=2 {g['id']} {field}: {g[field]} != swap2's {r[field]} shifted by {shift}"

    # N=2 exercises neither S_Y nor MARGIN — one row zeroes the spacing term, and with a
    # uniform world the margin is slack at every N below 32 — so matching swap2 does NOT
    # on its own make the formula right at every N. These are what only multi-row sizes
    # can violate, plus the density claim the uniform world is there to support.
    shape = yaml.safe_load(ROBOT.read_text())["shape"]
    body = math.hypot(shape["width"], shape["length"])  # rotation-invariant body diameter
    assert S_Y > body, f"row spacing {S_Y} <= unicycle_db body diameter {body:.4f}"
    for n in SIZES:
        world, x_left, x_right, ys = geometry(n)
        mid = world / 2
        assert abs((x_right - x_left) - TRAVERSE) < 1e-9, f"N={n} traverse != {TRAVERSE}"
        assert abs((x_left + x_right) / 2 - mid) < 1e-9, f"N={n} traverse off-centre"
        assert abs((ys[0] + ys[-1]) / 2 - mid) < 1e-9, f"N={n} rows off-centre"
        assert all(abs((b - a) - S_Y) < 1e-9 for a, b in zip(ys, ys[1:])), f"N={n} spacing"
        assert ys[0] >= MARGIN - 1e-9 and ys[-1] <= world - MARGIN + 1e-9, f"N={n} y margin"
        assert x_left >= MARGIN - 1e-9 and x_right <= world - MARGIN + 1e-9, f"N={n} x margin"
        assert world == WORLD, f"N={n} world {world} != uniform {WORLD}"
    # Free area per robot must fall monotonically with N, or "runtime vs N" is not a
    # congestion curve. This is the whole reason the world does not shrink with N.
    area = [WORLD**2 / n for n in SIZES]
    assert area == sorted(area, reverse=True), dict(zip(SIZES, area))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n", type=int, default=None, help=f"one size; default all of {SIZES}")
    ap.add_argument("--out-dir", type=Path, default=ROOT / "conf" / "env")
    args = ap.parse_args()

    check()
    # N=2 is swap2_unicycle2.yaml, already in the repo by hand. Emitting it as well would
    # give the same scenario two names, so it ships only if asked for by name.
    sizes = [args.n] if args.n else [n for n in SIZES if n != 2]
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for n in sizes:
        path = args.out_dir / f"open_cross_{n}_unicycle2.yaml"
        path.write_text(render(n))
        world, x_left, x_right, ys = geometry(n)
        print(f"{path.relative_to(ROOT)}  N={n}  world={num(world)}  rows={len(ys)}  "
              f"x {num(x_left)}->{num(x_right)}  y {num(ys[0])}..{num(ys[-1])}")


if __name__ == "__main__":
    main()
